kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operators-view
rules:
  - verbs:
      - list
      - watch
      - get
    apiGroups:
      - operators.coreos.com
    resources:
      - catalogsources
      - subscriptions
      - installplans
      - operatorgroups
      - clusterserviceversions