---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ printf "admins-%v" .Release.Namespace }}
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: {{ printf "admins-%v" .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
...
