kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operators-manage
subjects:
  # Note: this could also be a group
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: {{ printf "admins-%v" .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operators-manage
