kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operators-manage
rules:
  - verbs:
      - patch
      - update
      - get
    apiGroups:
      - operators.coreos.com
    resources:
      - installplans
      - clusterserviceversions