---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus-istio-system
  namespace: {{ .Release.Namespace }}
spec:
  name: prometheus-istio-system.yaml
  datasources:
    - name: prometheus-istio-system
      type: prometheus
      access: proxy
      url: http://prometheus-operated.{{ .Release.Namespace }}.svc:9090
      isDefault: true
      version: 1
      editable: false
      jsonData:
        tlsSkipVerify: true
        timeInterval: "5s"
