---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-monitoring-exporter-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.prometheus.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-monitoring-exporter-{{ .Release.Namespace }}
...