apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: sre-prometheus-{{ .Values.istio_control_plane.namespace }}
spec:
  labelSelector:
    matchLabels:
      maistra.io/member-of: {{ .Values.istio_control_plane.namespace }}
  templates:
  - objectTemplate: |
      kind: RoleBinding
      apiVersion: rbac.authorization.k8s.io/v1
      metadata:
        name: {{ .Values.prometheus.name }}
        namespace: {{ printf "%s" "{{ .Name }}" }}
      subjects:
      - kind: ServiceAccount
        namespace: {{ .Release.Namespace }}
        name: {{ .Values.prometheus.name }}
      roleRef:
        kind: ClusterRole
        name: {{ printf "%s-%s" "prometheus" .Values.istio_control_plane.namespace }}
        apiGroup: rbac.authorization.k8s.io